name: Branch Checks

on:
  push:
    branches-ignore:
      - master

# Prevent running checks for the same branch in parallel
# New workflows will cancel existing workflowsâ€¦
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup Docs
    uses: ./.github/workflows/setup-docs.yml

  build:
    name: Build (preview)
    uses: ./.github/workflows/build.yml
    secrets:
      NEXUS3_PW: ${{ secrets.NEXUS3_PW }}
      NEXUS_NPM_TOKEN_READ_ONLY: ${{ secrets.NEXUS_NPM_TOKEN_READ_ONLY }}
      MACDUFF_KEYCHAIN_PASSWORD: ${{ secrets.MACDUFF_KEYCHAIN_PASSWORD }}

  deploy:
    name: Deploy Docs Preview
    needs: [setup, build]
    uses: ./.github/workflows/deploy-docs-preview.yml
    # Do not deploy on forks
    if: ${{ !github.repository.fork }}
    permissions:
      actions: read
      pull-requests: write
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    with:
      alias: ${{ needs.setup.outputs.BRANCH_NAME_SLUG }}
      artifact_name: ${{ needs.build.outputs.docs_artifact_name }}
      artifact_path: ${{ needs.build.outputs.docs_artifact_path }}
      run_id: ${{ needs.build.outputs.run_id }}
      environment: main
